In [11]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
#check for GPU
if torch.cuda.is_available():
    print("GPU availbale")
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(device)

cpu


In [4]:
#starting with Tensors
#empty Tensor
a = torch.empty(2,3)

In [5]:
#type of Tensor Object
type(a)

torch.Tensor

In [8]:
#Zero Tensor
zero_tensor = torch.zeros(2,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#Ones Tensor
one_tensor = torch.ones(2,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#seeding
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

## Tensor Shape

In [12]:
#sometimes we need to create a similar shape of tensor
x = torch.tensor([[1,2,3],[1,2,3]])

In [16]:
x.shape

torch.Size([2, 3])

In [14]:
#now we want to create a similar kind of tensor
new_x = torch.empty_like(x)

In [17]:
new_x.shape

torch.Size([2, 3])